#!/usr/bin/env php
<?php

require __DIR__.'./vendor/autoload.php';

require __DIR__ . './bootstrap/app.php';

$app->start();

$console = new Core\Console\Console();

// start the console application
$console->run();
