#!/usr/bin/env php
<?php

require __DIR__.'./vendor/autoload.php';

require_once('./config/config.php');
define('DS',DIRECTORY_SEPARATOR);
define('ROOT',dirname(__FILE__));

function autoload($className){
    $classAry = explode('\\',$className);
    $class = array_pop($classAry);
    $subPath = strtolower(implode(DS,$classAry));
    $path = ROOT . DS . $subPath . DS . $class . '.php';
    if(file_exists($path)){
      require_once($path);
    }
  }

spl_autoload_register('autoload');


$console = new Core\Console();


// start the console application
$console->run();
